#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-temple
Version  : 0.7.6
Release  : 8
URL      : https://rubygems.org/downloads/temple-0.7.6.gem
Source0  : https://rubygems.org/downloads/temple-0.7.6.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-bacon
BuildRequires : rubygem-erubis
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-tilt

%description
Temple
======
[![Build Status](https://secure.travis-ci.org/judofyr/temple.png?branch=master)](http://travis-ci.org/judofyr/temple) [![Dependency Status](https://gemnasium.com/judofyr/temple.png?travis)](https://gemnasium.com/judofyr/temple) [![Code Climate](https://codeclimate.com/github/judofyr/temple.png)](https://codeclimate.com/github/judofyr/temple)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n temple-0.7.6
gem spec %{SOURCE0} -l --ruby > rubygem-temple.gemspec

%build
gem build rubygem-temple.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
temple-0.7.6.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/temple-0.7.6 && rake -I.:lib test && popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/temple-0.7.6.gem
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/.travis.yml
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/.yardopts
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/CHANGES
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/EXPRESSIONS.md
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/README.md
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/lib/temple.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/lib/temple/engine.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/lib/temple/erb/engine.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/lib/temple/erb/parser.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/lib/temple/erb/template.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/lib/temple/erb/trimming.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/lib/temple/exceptions.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/lib/temple/filter.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/lib/temple/filters/code_merger.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/lib/temple/filters/control_flow.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/lib/temple/filters/dynamic_inliner.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/lib/temple/filters/encoding.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/lib/temple/filters/eraser.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/lib/temple/filters/escapable.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/lib/temple/filters/multi_flattener.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/lib/temple/filters/remove_bom.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/lib/temple/filters/static_merger.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/lib/temple/filters/validator.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/lib/temple/generator.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/lib/temple/generators/array.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/lib/temple/generators/array_buffer.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/lib/temple/generators/erb.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/lib/temple/generators/rails_output_buffer.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/lib/temple/generators/string_buffer.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/lib/temple/grammar.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/lib/temple/html/attribute_merger.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/lib/temple/html/attribute_remover.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/lib/temple/html/attribute_sorter.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/lib/temple/html/dispatcher.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/lib/temple/html/fast.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/lib/temple/html/filter.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/lib/temple/html/pretty.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/lib/temple/html/safe.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/lib/temple/map.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/lib/temple/mixins/dispatcher.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/lib/temple/mixins/engine_dsl.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/lib/temple/mixins/grammar_dsl.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/lib/temple/mixins/options.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/lib/temple/mixins/template.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/lib/temple/parser.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/lib/temple/templates.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/lib/temple/templates/rails.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/lib/temple/templates/tilt.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/lib/temple/utils.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/lib/temple/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/temple.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/test/filters/test_code_merger.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/test/filters/test_control_flow.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/test/filters/test_dynamic_inliner.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/test/filters/test_eraser.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/test/filters/test_escapable.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/test/filters/test_multi_flattener.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/test/filters/test_static_merger.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/test/helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/test/html/test_attribute_merger.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/test/html/test_attribute_remover.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/test/html/test_attribute_sorter.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/test/html/test_fast.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/test/html/test_pretty.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/test/mixins/test_dispatcher.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/test/mixins/test_grammar_dsl.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/test/test_engine.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/test/test_erb.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/test/test_filter.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/test/test_generator.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/test/test_grammar.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/test/test_map.rb
/usr/lib64/ruby/gems/2.3.0/gems/temple-0.7.6/test/test_utils.rb
/usr/lib64/ruby/gems/2.3.0/specifications/temple-0.7.6.gemspec
